// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace CombatSystemGameplayTags
{
	//Input Tags

	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	//Player Tags
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe)
	
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	COMBATSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
}
